import { StyleSheet } from "react-native";

export default containerStyles=StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'column'
    }, 
    formContianerInp:{
        width:'80%',
        height:'90%',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'space-around'
    },
    inptField:{
        width:'100%',
        height:45,
        backgroundColor:'#E7F0E9',
        borderRadius:10,
        paddingLeft:10,
        borderColor:'#000000',
        borderWidth:1
    },
    inputContainer:{
        width:'90%',
        height:'25%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-around'
    },
    textInput:{
        fontSize:18,
    },
    logoLogin:{
        width:130,
        height:130,
        borderRadius:20,
        overflow:'hidden'
       },
       imageLoginLogo:{
        width:'100%',
        height:'100%',
     },
     new_into_app:{
      width:'40%',
      height:40,
      backgroundColor:'#6AC52D',
      display:'flex',
      justifyContent:'center',
      alignItems:'center',
      borderRadius:10,
     },
     modalContainer:{
        width:'100%',
        height:'100%',
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
     },
     boxAlert:{
        width:'80%',
        height:'60%',
        borderRadius:10,
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-around',
        alignItems:'center',
        backgroundColor:'#dddddd'
     },
     logoAlert:{
        width:'50%',
        height:'40%',
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
     },
     infoAlert:{
        width:'90%',
        height:'35%',
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
     }
})