import {StyleSheet} from 'react-native';

export default actualValues=StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center'
    },
    navBar:{
        width:'100%',
        height:50,
        backgroundColor:'#6AC52D',
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    appName:{
        width:'60%',
        fontSize:22,
        display:'flex',
        textAlign:'right'
    },
    logoProfile:{
        width:35,
        height:35,
        borderRadius:35,
        backgroundColor:'#2e4a21',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        marginRight:10,
    },
    statusAndPoints:{
        width:'90%',
        height:'30%',
        display:'flex',
        flexDirection:'column',
    },
    progress:{
        width:'90%',
        height:'25%',
        borderBottomWidth:1,
        borderBottomColor:'#0A8156'
    },  
    fontProgress:{
        fontSize:20,
        fontWeight:600,
        color:'#2E4A21'
    },
    miniData:{
        width:'90%',
        height:'20%',
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
    },
    userWelcome:{
        width:'100%',
        height:'40%',
        display:'flex',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center'
    },
    userStats:{
        width:'100%',
        height:'60%',
        borderColor:'#0A8156',
        borderWidth:1,
        borderRadius:10,
        display:'flex',
        flexDirection:'column',
        overflow:'hidden'
    },
    pointContainer:{
        width:'100%',
        height:'50%',
        backgroundColor:'#6AC52D',
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center'
    },
    growStatus:{
        width:'100%',
        height:'50%',
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center'
    },
    fontWelcomeUser:{
        fontSize:24,
        fontWeight:600,
        color:'#2E4A21'
    },
    advancedStatus:{
        width:'100%',
        height:'80%',
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
    },
    displayLevelStatus:{
        width:'30%',
        height:'90%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-evenly',
        alignItems:'center'
    },
    titleLevel:{
        width:'100%',
        height:'20%',
        fontSize:18,
        fontWeight:600,
        textAlign:'center',
    },
    circleLevel:{
        width:200,
        height:70,
        margin:'auto',
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
    
    },
    poinsText:{
        fontSize:20,
        color:'#000000',
        fontWeight:600
    },
    growText:{
        fontSize:20,
        color:'#0A8156',
        fontWeight:600
    },
    amountBotles:{
        color:'#6AC52D',
        fontWeight:'bold',
        fontSize:40,
    },
    percentData:{
        width:'80%',
        height:'90%',
      
        display:'flex',
        justifyContent:'space-around',
        alignItems:'center',
        flexDirection:'row'
    },
    boxPercentageType:{
        width:'45%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center'
    },
    numberPercentage:{
        fontSize:30,
        color:'#000000',
        fontWeight:'bold',
    }
})